title: Write-ups - Huỳnh Thanh Giang
description: HackTheBox & TryHackMe Write-ups
baseurl: "" 
url: "https://huynhthanhgiang41k2.github.io"

theme: minima   # theme mặc định đơn giản của GitHub, sau này có thể đổi

# Cấu hình categories
defaults:
  - scope:
      path: ""
    values:
      layout: "post"

collections:
  writeups:
    output: true
    permalink: /writeups/:path/
